sudo: false
language: node_js
node_js:
- 12
cache: yarn
branches:
  only:
  - master
before_install:
  - openssl aes-256-cbc -K $encrypted_db8d9b5ea11f_key -iv $encrypted_db8d9b5ea11f_iv
    -in id_rsa.enc -out ~\/.ssh/id_rsa -d
install:
- yarn install
script:
- yarn build
after_success:
- mkdir dist
- cp -r .next/ dist/.next
- cp package.json dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  target_branch: DEPLOY-PROD
  committer_from_gh: true
  on:
    branch: master
  local_dir: dist
after_deploy:
  ssh root@119.28.222.199 'pwd'
