sudo: false
language: node_js
node_js:
  - 12
cache: yarn
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_db8d9b5ea11f_key -iv $encrypted_db8d9b5ea11f_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  #降低id_rsa文件的权限，否则ssh处于安全方面的原因会拒绝读取秘钥
  - chmod 600 ~/.ssh/id_rsa
  #将生产服务器地址加入到构建机的信任列表中，否则连接时会询问是否信任服务器
  - echo -e "Host $PROD_SERVER_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - yarn global add pm2
  - yarn install
script:
  - yarn build
after_success:
  - mkdir dist
  - cp -r .next/ dist/.next
  - cp package.json dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: true
  target_branch: DEPLOY-PROD
  committer_from_gh: true
  on:
    branch: master
  local_dir: dist
after_deploy:
  - pm2 deploy ecosystem.config.js prod update --force

